package simpledb.execution;

import simpledb.common.DbException;
import simpledb.storage.Tuple;
import simpledb.storage.TupleDesc;
import simpledb.transaction.TransactionAbortedException;

import java.util.NoSuchElementException;

/**
 * The Join operator implements the relational join operation.
 */
public class Join extends Operator {

    private static final long serialVersionUID = 1L;

    private JoinPredicate p;

    private OpIterator child1;

    private OpIterator child2;

    private TupleDesc tupleDesc1;

    private TupleDesc tupleDesc2;

    /**
     * Constructor. Accepts two children to join and the predicate to join them
     * on
     *
     * @param p      The predicate to use to join the children
     * @param child1 Iterator for the left(outer) relation to join
     * @param child2 Iterator for the right(inner) relation to join
     */
    public Join(JoinPredicate p, OpIterator child1, OpIterator child2) {
        // TODO: some code goes here
        this.p = p;
        this.child1 = child1;
        this.child2 = child2;
        tupleDesc1 = child1.getTupleDesc();
        tupleDesc2 = child2.getTupleDesc();
    }

    public JoinPredicate getJoinPredicate() {
        // TODO: some code goes here
        return p;
    }

    /**
     * @return the field name of join field1. Should be quantified by
     * alias or table name.
     */
    public String getJoinField1Name() {
        // TODO: some code goes here
        return tupleDesc1.getFieldName(p.getField1());
    }

    /**
     * @return the field name of join field2. Should be quantified by
     * alias or table name.
     */
    public String getJoinField2Name() {
        // TODO: some code goes here
        return tupleDesc2.getFieldName(p.getField2());
    }

    /**
     * @see TupleDesc#merge(TupleDesc, TupleDesc) for possible
     * implementation logic.
     */
    public TupleDesc getTupleDesc() {
        // TODO: some code goes here
        return TupleDesc.merge(tupleDesc1, tupleDesc2);
    }

    public void open() throws DbException, NoSuchElementException, TransactionAbortedException {
        // TODO: some code goes here
        super.open();
        child1.open();
        child2.open();
    }

    public void close() {
        // TODO: some code goes here
        super.close();
        child1.close();
        child2.close();
    }

    public void rewind() throws DbException, TransactionAbortedException {
        // TODO: some code goes here
        child1.rewind();
        child2.rewind();
    }

    private Tuple t;

    /**
     * Returns the next tuple generated by the join, or null if there are no
     * more tuples. Logically, this is the next tuple in r1 cross r2 that
     * satisfies the join predicate. There are many possible implementations;
     * the simplest is a nested loops join.
     * <p>
     * Note that the tuples returned from this particular implementation of Join
     * are simply the concatenation of joining tuples from the left and right
     * relation. Therefore, if an equality predicate is used there will be two
     * copies of the join attribute in the results. (Removing such duplicate
     * columns can be done with an additional projection operator if needed.)
     * <p>
     * For example, if one tuple is {1,2,3} and the other tuple is {1,5,6},
     * joined on equality of the first column, then this returns {1,2,3,1,5,6}.
     *
     * @return The next matching tuple.
     * @see JoinPredicate#filter
     */
    protected Tuple fetchNext() throws TransactionAbortedException, DbException {
        // TODO: some code goes here
//        Tuple tuple = null;
//        Tuple tuple2 = null;
//        while (child1.hasNext()) {
//            if (tuple == null || isUpdate) {
//                tuple = child1.next();
//            }
//            while (child2.hasNext()) {
//                tuple2 = child2.next();
//                if (p.filter(tuple, tuple2)) {
//                    Tuple newTuple = new Tuple(this.getTupleDesc());
//                    int l1 = tuple.getTupleDesc().numFields();
//                    int l2 = tuple2.getTupleDesc().numFields();
//                    int i = 0;
//                    for (; i < l1; i++) {
//                        newTuple.setField(i, tuple.getField(i));
//                    }
//                    for (int j = 0; j < l2; j++) {
//                        newTuple.setField(i + j, tuple2.getField(j));
//                    }
//                    isUpdate = !child2.hasNext();
//                    return newTuple;
//                }
//            }
//            isUpdate = true;
//            child2.rewind();
//        }
//        return null;
        while (this.child1.hasNext() || this.t != null) {
            if (this.child1.hasNext() && this.t == null) {
                t = child1.next();
            }
            while (child2.hasNext()) {
                Tuple t2 = child2.next();
                if (p.filter(t, t2)) {
                    TupleDesc td1 = t.getTupleDesc();
                    TupleDesc td2 = t2.getTupleDesc();
                    TupleDesc newTd = TupleDesc.merge(td1, td2);
                    Tuple newTuple = new Tuple(newTd);
                    int i = 0;
                    for (; i < td1.numFields(); i++) {
                        newTuple.setField(i, t.getField(i));
                    }
                    for (int j = 0; j < td2.numFields(); j++) {
                        newTuple.setField(i + j, t2.getField(j));
                    }
                    return newTuple;
                }
            }
            child2.rewind();
            t = null;
        }
        return null;
    }

    @Override
    public OpIterator[] getChildren() {
        // TODO: some code goes here
        return new OpIterator[]{child1, child2};
    }

    @Override
    public void setChildren(OpIterator[] children) {
        // TODO: some code goes here
        child1 = children[0];
        child2 = children[1];
    }

}
